apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: "15s" 
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data: 
    - secretKey: DB_NAME
      remoteRef:
        key: laranetes/mysql
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: laranetes/mysql
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: laranetes/mysql
        property: DB_PASSWORD
